#install nodejs
FROM ubuntu
RUN apt-get update
#RUN apt-get install -y software-properties-common
#RUN add-apt-repository ppa:libreoffice/ppa
#RUN apt-get update
#RUN apt-get install -y --force-yes libreoffice
#RUN apt-get clean

RUN apt-get install -y nodejs npm
RUN apt-get install -y pdftk
RUN apt-get install -y poppler-utils
RUN apt-get install -y tesseract-ocr
RUN apt-get install -y ghostscript
RUN apt-get install -y nano

RUN mkdir -p /edokyu
RUN mkdir -p /drive

WORKDIR /edokyu
COPY package.json /edokyu
RUN npm install
COPY . /edokyu
COPY /temp/drive/. /drive

#RUN apt-get purge mongodb
#RUN apt-get install -y gnupg
#RUN apt-get install -y wget
#RUN wget -qO - http://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
#RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
#RUN apt-get update
#RUN apt-get install -y --force-yes mongodb-org
#RUN /etc/init.d/mongodb start
#RUN systemctl enable mongodb

#RUN /etc/init.d/mongodb start
#RUN /edokyu/data/restore.sh

EXPOSE 80
EXPOSE 443
#CMD ["sh", "/etc/init.d/mongodb start"]
#CMD ["node", "index.js"]


