#install nodejs
FROM ubuntu:20.04
EXPOSE 80:80
EXPOSE 443:443
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:libreoffice/ppa
RUN apt-get update
RUN apt-get install -y --force-yes libreoffice
RUN apt-get clean

RUN apt-get install -y nodejs npm
RUN apt-get install -y pdftk
RUN apt-get install -y poppler-utils
RUN apt-get install -y tesseract-ocr
RUN apt-get install -y ghostscript
RUN apt-get install -y nano

RUN mkdir -p /edokyu
RUN mkdir -p /drive

WORKDIR /edokyu
COPY package.json /edokyu
RUN npm install
COPY . /edokyu
COPY /temp/drive/. /drive

RUN apt-get install -y mongodb
#RUN service mongodb start

#RUN /etc/init.d/mongodb start
RUN chmod ugo+x data/restore.sh
RUN data/restore.sh

#CMD ["sh", "/edokyu/data/restore.sh"]
#CMD ["sh", "/etc/init.d/mongodb start"]
CMD ["sh", "start.sh"]

